development:
  adapter: sqlite3
  encoding: utf8
  database: dog-api_development.db
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: 'DATABASE_URL'
  pool: 5
  host: localhost
