#development:
#  adapter: sqlite3
#  encoding: utf8
#  database: randomanimal-api_development.db
#  pool: 5
#  username:
#  password:

development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

#production:
#  adapter: postgresql
#  encoding: utf8
#  database: <%= ENV['DB_NAME'] %>
#  pool: 5
#  username: <%= ENV['DB_USERNAME'] %>
#  password: <%= ENV['DB_PASSWORD'] %>
#  host: <%= ENV['DB_HOST'] %>
